const translations = {
    pt: {
        doc_title_dashboard: "Dashboard",
        doc_title_books: "Livros",
        doc_title_publishers: "Editoras",
        doc_title_rentals: "Aluguéis",
        doc_title_users: "Usuários",
        doc_title_settings: "Configurações",
        doc_title_forgot_pwd: "Esqueci Senha",
        doc_title_login: "Login",
        doc_title_register: "Cadastro",
        header_title: "Biblioteca Dashboard",
        header_title_books: "Biblioteca Listar Livros",
        header_title_publishers: "Biblioteca Listar Editoras",
        header_title_rentals: "Biblioteca Listar Aluguéis",
        header_title_users: "Biblioteca Usuários",
        header_title_settings: "Biblioteca Configurações",
        header_title_forgot_pwd: "Biblioteca Esqueci Senha",
        header_title_login: "Biblioteca Login",
        header_title_register: "Biblioteca Cadastro",
        nav_user: "Usuário",
        nav_settings: "Ajustes",
        nav_logout: "Sair",
        menu_publishers: "Editoras",
        menu_books: "Livros",
        menu_users: "Usuários",
        menu_rentals: "Aluguéis",
        menu_dashboard: "Dashboard",
        card_ontime: "Quantidade de Aluguéis em Dia:",
        card_ontime_val: "275 Aluguéis",
        card_expiring: "Quantidade de Aluguéis Perto de Vencer:",
        card_expiring_val: "100 Aluguéis",
        card_late: "Quantidade de Aluguéis em Atraso:",
        card_late_val: "10 Aluguéis",
        badge_ontime: "EM DIA",
        badge_warning: "PERTO DE VENCER",
        badge_late: "ATRASADO",
        status_active: "Ativo",
        status_activated: "ATIVADO",
        status_row_pattern: "Livro | Data do início do prazo | Data final do prazo",
        box_latest_rentals: "Últimos Livros Alugados",
        box_globals: "Quantitativos Globais",
        global_rentals: "Aluguéis Realizados",
        global_books: "Livros Cadastrados",
        global_publishers: "Editoras Cadastradas",
        box_qty_books: "Quantidade de Livros Alugados",
        box_qty_books_rent: "Quantidade de Livros Para Alugar",
        box_most_rented: "Livro Mais Alugado",
        box_status_rentals: "Status dos Aluguéis",
        col_code: "Cód.",
        col_id: "ID",
        col_book_name: "Nome do Livro",
        col_user_name: "Nome do Usuário",
        col_book: "Livro",
        col_publisher: "Editora",
        col_release_date: "Data de Lançamento",
        col_start_date: "Data Início",
        col_end_date: "Data Fim",
        col_status: "Status",
        col_cpf: "CPF",
        col_birth_date: "Data de Nasc.",
        col_contact: "E-mail/Telefone",
        col_address: "Endereço",
        col_actions: "Ações",
        page_prefix: "1 de",
        placeholder_search_book: "pesquisar livro...",
        placeholder_search_publisher: "pesquisar editora...",
        placeholder_search_rental: "Pesquisar Aluguel...",
        placeholder_search_users: "pesquisar usuários...",
        placeholder_full_name: "Nome Completo",
        placeholder_address_format: "Logradouro, Nº - Bairro",
        placeholder_current_pwd: "Digite sua senha atual",
        placeholder_new_pwd: "Digite a nova senha",
        placeholder_confirm_pwd: "Confirme a nova senha",
        placeholder_password: "senha",
        placeholder_support_msg: "Descreva sua solicitação...",
        btn_new_book: "+ Novo Livro",
        btn_new_publisher: "+ Nova Editora",
        btn_new_rental: "+ Novo Aluguel",
        btn_edit: "Editar",
        btn_delete: "Excluir",
        btn_return: "Devolver",
        btn_activate: "ATIVAR",
        btn_activated: "ATIVADO",
        btn_deactivate: "DESATIVAR",
        btn_deactivated: "DESATIVADO",
        btn_confirm: "CONFIRMAR",
        btn_cancel: "CANCELAR",
        btn_confirm_delete: "EXCLUIR",
        btn_theme_light: "Claro",
        btn_theme_dark: "Escuro",
        btn_send: "Enviar",
        btn_close: "Fechar",
        btn_confirm_action: "Confirmar",
        btn_cancel_action: "Cancelar",
        btn_edit_info: "Editar Informações",
        btn_login: "Entrar",
        btn_register: "Cadastre-se",
        btn_submit_register: "Cadastrar",
        title_settings: "Configurações",
        tab_profile: "Perfil",
        tab_accessibility: "Acessibilidade",
        label_system_theme: "Cor do Sistema: ",
        label_system_language: "Idioma do Sistema: ",
        opt_select: "Selecione",
        title_create_book: "Criar Livro",
        title_create_publisher: "Criar Editora",
        title_create_rental: "Criar Aluguel:",
        title_form_register: "Cadastre-se",
        modal_create_book_title: "Criar Livro",
        modal_delete_book_title: "Excluir Livro",
        modal_create_publisher_title: "Criar Editora",
        modal_delete_publisher_title: "Excluir Editora",
        modal_create_rental_title: "Criar Aluguel",
        modal_delete_rental_title: "Excluir Aluguel",
        modal_return_rental_title: "Confirmar Devolução",
        modal_change_status_title: "Alterar Status",
        modal_support_title: "Suporte ao Usuário",
        modal_support_desc: "Informe seu e-mail e descreva o motivo do contato para nossa equipe ajudar você.",
        label_full_name: "Nome Completo:",
        label_location: "Localização:",
        label_book_title: "Título do Livro:",
        label_publisher: "Editora:",
        label_release_date: "Data de Lançamento:",
        label_quantity: "Quantidade:",
        label_form_book_name: "Nome do Livro:",
        label_form_book_cod: "Código do Livro:",
        label_form_publisher: "Editora:",
        label_form_release_date: "Data de Lançamento:",
        label_form_publisher_name: "Nome da Editora:",
        label_form_publisher_cnpj: "CNPJ da Editora:",
        label_form_email: "E-mail:",
        label_form_phone: "Telefone:",
        label_form_address: "Endereço:",
        label_form_user_name: "Nome do Usuário:",
        label_form_user_cpf: "CPF do Usuário:",
        label_form_return_date: "Data de Devolução:",
        label_email: "E-mail:",
        label_phone: "Telefone:",
        label_birth_date: "Data de Nascimento:",
        label_cpf: "CPF:",
        label_address: "Endereço:",
        label_old_password: "Senha Antiga:",
        label_new_password: "Nova Senha:",
        label_confirm_password: "Confirmar Senha:",
        label_password: "Senha:",
        label_support_email: "Seu E-mail:",
        label_support_msg: "Situação / Dúvida:",
        label_cod_summary: "Cód.:",
        label_book_summary: "Livro:",
        label_id_summary: "ID:",
        label_publisher_summary: "Editora:",
        label_user_summary: "Usuário:",
        tooltip_support_change: "Caso queira trocar, contate o suporte.",
        link_need_help: "Quer ajuda?",
        link_forgot_password: "esqueci senha",
        divider_or: "----ou----",
        divider_or_long: "----------------ou-----------------",
        msg_confirm_delete_book: "Tem certeza de que deseja excluir este livro?",
        msg_warning_delete_book: "Esta ação removerá o livro do catálogo.",
        msg_confirm_delete_publisher: "Tem certeza de que deseja excluir esta editora?",
        msg_warning_delete_irreversible: "Esta ação não poderá ser desfeita.",
        msg_confirm_delete_rental: "Tem certeza de que deseja excluir este registro de aluguel?",
        msg_confirm_return_rental: "Deseja confirmar a devolução deste livro?",
        msg_confirm_change_status: "Deseja alterar o status deste usuário?",
        msg_warning_change_status: "O usuário perderá o acesso caso seja desativado.",
        banner_welcome: "Bem Vindo(a)",
        banner_line2: "A Leitura Abre",
        banner_line3: "Novos Mundos",
        banner_line4: "Acesse sua conta e assista a sua experiência",
        title_recover_pwd: "Recuperar Senha",
        title_form_welcome: "Bem Vindo(a)!",
        footer_about_title: "Sobre Nós",
        footer_about_mobile: "Criando valor e inspiração desde 2023.",
        footer_about_desktop: "Criando valor e inspiração desde 2023.\nNossa missão é informar você aos seus produtos com praticidade.",
        footer_contact_title: "Contate-Nos",
        footer_locations_title: "Nossos Locais",
        location_1: "Rua Padre Filho, 263- Centro",
        location_2: "Rua IV, 60- Paulista",
        location_3: "Rua Norte Europeu, 110 - Vale Central"
    },
    en: {
        doc_title_dashboard: "Dashboard",
        doc_title_books: "Books",
        doc_title_publishers: "Publishers",
        doc_title_rentals: "Rentals",
        doc_title_users: "Users",
        doc_title_settings: "Settings",
        doc_title_forgot_pwd: "Forgot Password",
        doc_title_login: "Login",
        doc_title_register: "Register",
        header_title: "Library Dashboard",
        header_title_books: "Library List Books",
        header_title_publishers: "Library List Publishers",
        header_title_rentals: "Library List Rentals",
        header_title_users: "Library Users",
        header_title_settings: "Library Settings",
        header_title_forgot_pwd: "Library Forgot Password",
        header_title_login: "Library Login",
        header_title_register: "Library Register",
        nav_user: "User",
        nav_settings: "Settings",
        nav_logout: "Logout",
        menu_publishers: "Publishers",
        menu_books: "Books",
        menu_users: "Users",
        menu_rentals: "Rentals",
        menu_dashboard: "Dashboard",
        card_ontime: "Rentals On Schedule:",
        card_ontime_val: "275 Rentals",
        card_expiring: "Rentals Expiring Soon:",
        card_expiring_val: "100 Rentals",
        card_late: "Overdue Rentals:",
        card_late_val: "10 Rentals",
        badge_ontime: "ON SCHEDULE",
        badge_warning: "EXPIRING SOON",
        badge_late: "OVERDUE",
        status_active: "Active",
        status_activated: "ACTIVATED",
        status_row_pattern: "Book | Start deadline date | End deadline date",
        box_latest_rentals: "Latest Rented Books",
        box_globals: "Global Quantities",
        global_rentals: "Completed Rentals",
        global_books: "Registered Books",
        global_publishers: "Registered Publishers",
        box_qty_books: "Number of Rented Books",
        box_qty_books_rent: "Number of Books Available to Rent",
        box_most_rented: "Most Rented Book",
        box_status_rentals: "Rentals Status",
        col_code: "Code",
        col_id: "ID",
        col_book_name: "Book Title",
        col_user_name: "User Name",
        col_book: "Book",
        col_publisher: "Publisher",
        col_release_date: "Release Date",
        col_start_date: "Start Date",
        col_end_date: "End Date",
        col_status: "Status",
        col_cpf: "CPF / ID",
        col_birth_date: "Birth Date",
        col_contact: "Email/Phone",
        col_address: "Address",
        col_actions: "Actions",
        page_prefix: "1 of",
        placeholder_search_book: "search book...",
        placeholder_search_publisher: "search publisher...",
        placeholder_search_rental: "Search Rental...",
        placeholder_search_users: "search users...",
        placeholder_full_name: "Full Name",
        placeholder_address_format: "Street, Number - District",
        placeholder_current_pwd: "Enter current password",
        placeholder_new_pwd: "Enter new password",
        placeholder_confirm_pwd: "Confirm new password",
        placeholder_password: "password",
        placeholder_support_msg: "Describe your request...",
        btn_new_book: "+ New Book",
        btn_new_publisher: "+ New Publisher",
        btn_new_rental: "+ New Rental",
        btn_edit: "Edit",
        btn_delete: "Delete",
        btn_return: "Return",
        btn_activate: "ACTIVATE",
        btn_activated: "ACTIVATED",
        btn_deactivate: "DEACTIVATE",
        btn_deactivated: "DEACTIVATED",
        btn_confirm: "CONFIRM",
        btn_cancel: "CANCEL",
        btn_confirm_delete: "DELETE",
        btn_theme_light: "Light",
        btn_theme_dark: "Dark",
        btn_send: "Send",
        btn_close: "Close",
        btn_confirm_action: "Confirm",
        btn_cancel_action: "Cancel",
        btn_edit_info: "Edit Information",
        btn_login: "Log In",
        btn_register: "Register",
        btn_submit_register: "Register",
        title_settings: "Settings",
        tab_profile: "Profile",
        tab_accessibility: "Accessibility",
        label_system_theme: "System Theme: ",
        label_system_language: "System Language: ",
        opt_select: "Select",
        title_create_book: "Create Book",
        title_create_publisher: "Create Publisher",
        title_create_rental: "Create Rental:",
        title_form_register: "Register",
        modal_create_book_title: "Create Book",
        modal_delete_book_title: "Delete Book",
        modal_create_publisher_title: "Create Publisher",
        modal_delete_publisher_title: "Delete Publisher",
        modal_create_rental_title: "Create Rental",
        modal_delete_rental_title: "Delete Rental",
        modal_return_rental_title: "Confirm Return",
        modal_change_status_title: "Change Status",
        modal_support_title: "User Support",
        modal_support_desc: "Enter your email and describe the reason for contact so our team can assist you.",
        label_full_name: "Full Name:",
        label_location: "Location:",
        label_book_title: "Book Title:",
        label_publisher: "Publisher:",
        label_release_date: "Release Date:",
        label_quantity: "Quantity:",
        label_form_book_name: "Book Title:",
        label_form_book_cod: "Book Code:",
        label_form_publisher: "Publisher:",
        label_form_release_date: "Release Date:",
        label_form_publisher_name: "Publisher Name:",
        label_form_publisher_cnpj: "Publisher Tax ID:",
        label_form_email: "Email:",
        label_form_phone: "Phone:",
        label_form_address: "Address:",
        label_form_user_name: "User Name:",
        label_form_user_cpf: "User CPF / ID:",
        label_form_return_date: "Return Date:",
        label_email: "Email:",
        label_phone: "Phone:",
        label_birth_date: "Birth Date:",
        label_cpf: "CPF / ID:",
        label_address: "Address:",
        label_old_password: "Old Password:",
        label_new_password: "New Password:",
        label_confirm_password: "Confirm Password:",
        label_password: "Password:",
        label_support_email: "Your Email:",
        label_support_msg: "Issue / Question:",
        label_cod_summary: "Code:",
        label_book_summary: "Book:",
        label_id_summary: "ID:",
        label_publisher_summary: "Publisher:",
        label_user_summary: "User:",
        tooltip_support_change: "If you wish to change this, please contact support.",
        link_need_help: "Need help?",
        link_forgot_password: "forgot password",
        divider_or: "----or----",
        divider_or_long: "----------------or-----------------",
        msg_confirm_delete_book: "Are you sure you want to delete this book?",
        msg_warning_delete_book: "This action will remove the book from the catalog.",
        msg_confirm_delete_publisher: "Are you sure you want to delete this publisher?",
        msg_warning_delete_irreversible: "This action cannot be undone.",
        msg_confirm_delete_rental: "Are you sure you want to delete this rental record?",
        msg_confirm_return_rental: "Do you want to confirm the return of this book?",
        msg_confirm_change_status: "Do you want to change the status of this user?",
        msg_warning_change_status: "The user will lose access if deactivated.",
        banner_welcome: "Welcome",
        banner_line2: "Reading Opens",
        banner_line3: "New Worlds",
        banner_line4: "Access your account and enjoy your experience",
        title_recover_pwd: "Recover Password",
        title_form_welcome: "Welcome!",
        footer_about_title: "About Us",
        footer_about_mobile: "Creating value and inspiration since 2023.",
        footer_about_desktop: "Creating value and inspiration since 2023.\nOur mission is to connect you to your products with convenience.",
        footer_contact_title: "Contact Us",
        footer_locations_title: "Our Locations",
        location_1: "Padre Filho Street, 263 - Downtown",
        location_2: "4th Street, 60 - Paulista",
        location_3: "North European Street, 110 - Central Valley"
    },
    es: {
        doc_title_dashboard: "Panel",
        doc_title_books: "Libros",
        doc_title_publishers: "Editoriales",
        doc_title_rentals: "Alquileres",
        doc_title_users: "Usuarios",
        doc_title_settings: "Configuración",
        doc_title_forgot_pwd: "Olvidé Contraseña",
        doc_title_login: "Iniciar Sesión",
        doc_title_register: "Registro",
        header_title: "Panel de Biblioteca",
        header_title_books: "Biblioteca Listar Libros",
        header_title_publishers: "Biblioteca Listar Editoriales",
        header_title_rentals: "Biblioteca Listar Alquileres",
        header_title_users: "Usuarios de Biblioteca",
        header_title_settings: "Biblioteca Configuración",
        header_title_forgot_pwd: "Biblioteca Olvidé Contraseña",
        header_title_login: "Iniciar Sesión en Biblioteca",
        header_title_register: "Biblioteca Registro",
        nav_user: "Usuario",
        nav_settings: "Ajustes",
        nav_logout: "Salir",
        menu_publishers: "Editoriales",
        menu_books: "Libros",
        menu_users: "Usuarios",
        menu_rentals: "Alquileres",
        menu_dashboard: "Panel",
        card_ontime: "Alquileres al Día:",
        card_ontime_val: "275 Alquileres",
        card_expiring: "Alquileres por Vencer:",
        card_expiring_val: "100 Alquileres",
        card_late: "Alquileres Atrasados:",
        card_late_val: "10 Alquileres",
        badge_ontime: "AL DÍA",
        badge_warning: "POR VENCER",
        badge_late: "ATRASADO",
        status_active: "Activo",
        status_activated: "ACTIVADO",
        status_row_pattern: "Libro | Fecha de inicio del plazo | Fecha final del plazo",
        box_latest_rentals: "Últimos Libros Alquilados",
        box_globals: "Cuantitativos Globales",
        global_rentals: "Alquileres Realizados",
        global_books: "Libros Registrados",
        global_publishers: "Editoriales Registradas",
        box_qty_books: "Cantidad de Libros Alquilados",
        box_qty_books_rent: "Cantidad de Libros para Alquilar",
        box_most_rented: "Libro Más Alquilado",
        box_status_rentals: "Estado de Alquileres",
        col_code: "Cód.",
        col_id: "ID",
        col_book_name: "Nombre del Libro",
        col_user_name: "Nombre del Usuario",
        col_book: "Libro",
        col_publisher: "Editorial",
        col_release_date: "Fecha de Lanzamiento",
        col_start_date: "Fecha Inicio",
        col_end_date: "Fecha Fin",
        col_status: "Estado",
        col_cpf: "DNI / CIF",
        col_birth_date: "Fecha de Nac.",
        col_contact: "Email/Teléfono",
        col_address: "Dirección",
        col_actions: "Acciones",
        page_prefix: "1 de",
        placeholder_search_book: "buscar libro...",
        placeholder_search_publisher: "buscar editorial...",
        placeholder_search_rental: "Buscar Alquiler...",
        placeholder_search_users: "buscar usuarios...",
        placeholder_full_name: "Nombre Completo",
        placeholder_address_format: "Calle, Nº - Barrio",
        placeholder_current_pwd: "Escriba su contraseña actual",
        placeholder_new_pwd: "Escriba la nueva contraseña",
        placeholder_confirm_pwd: "Confirme la nueva contraseña",
        placeholder_password: "contraseña",
        placeholder_support_msg: "Describa su solicitud...",
        btn_new_book: "+ Nuevo Libro",
        btn_new_publisher: "+ Nueva Editorial",
        btn_new_rental: "+ Nuevo Alquiler",
        btn_edit: "Editar",
        btn_delete: "Eliminar",
        btn_return: "Devolver",
        btn_activate: "ACTIVAR",
        btn_activated: "ACTIVADO",
        btn_deactivate: "DESACTIVAR",
        btn_deactivated: "DESACTIVADO",
        btn_confirm: "CONFIRMAR",
        btn_cancel: "CANCELAR",
        btn_confirm_delete: "ELIMINAR",
        btn_theme_light: "Claro",
        btn_theme_dark: "Oscuro",
        btn_send: "Enviar",
        btn_close: "Cerrar",
        btn_confirm_action: "Confirmar",
        btn_cancel_action: "Cancelar",
        btn_edit_info: "Editar Información",
        btn_login: "Iniciar Sesión",
        btn_register: "Registrarse",
        btn_submit_register: "Registrarse",
        title_settings: "Configuración",
        tab_profile: "Perfil",
        tab_accessibility: "Accesibilidad",
        label_system_theme: "Color del Sistema: ",
        label_system_language: "Idioma del Sistema: ",
        opt_select: "Seleccione",
        title_create_book: "Crear Libro",
        title_create_publisher: "Crear Editorial",
        title_create_rental: "Crear Alquiler:",
        title_form_register: "Registrarse",
        modal_create_book_title: "Crear Libro",
        modal_delete_book_title: "Eliminar Libro",
        modal_create_publisher_title: "Crear Editorial",
        modal_delete_publisher_title: "Eliminar Editorial",
        modal_create_rental_title: "Crear Alquiler",
        modal_delete_rental_title: "Eliminar Alquiler",
        modal_return_rental_title: "Confirmar Devolución",
        modal_change_status_title: "Cambiar Estado",
        modal_support_title: "Soporte al Usuario",
        modal_support_desc: "Indique su correo y describa el motivo de contacto para que nuestro equipo le ayude.",
        label_full_name: "Nombre Completo:",
        label_location: "Ubicación:",
        label_book_title: "Título del Libro:",
        label_publisher: "Editorial:",
        label_release_date: "Fecha de Lanzamiento:",
        label_quantity: "Cantidad:",
        label_form_book_name: "Nombre del Libro:",
        label_form_book_cod: "Código del Libro:",
        label_form_publisher: "Editorial:",
        label_form_release_date: "Fecha de Lanzamiento:",
        label_form_publisher_name: "Nombre de la Editorial:",
        label_form_publisher_cnpj: "CIF / Identificación:",
        label_form_email: "Email:",
        label_form_phone: "Teléfono:",
        label_form_address: "Dirección:",
        label_form_user_name: "Nombre del Usuario:",
        label_form_user_cpf: "DNI del Usuario:",
        label_form_return_date: "Fecha de Devolución:",
        label_email: "Email:",
        label_phone: "Teléfono:",
        label_birth_date: "Fecha de Nacimiento:",
        label_cpf: "DNI / CIF:",
        label_address: "Dirección:",
        label_old_password: "Contraseña Anterior:",
        label_new_password: "Nueva Contraseña:",
        label_confirm_password: "Confirmar Contraseña:",
        label_password: "Contraseña:",
        label_support_email: "Su Email:",
        label_support_msg: "Situación / Duda:",
        label_cod_summary: "Cód.:",
        label_book_summary: "Libro:",
        label_id_summary: "ID:",
        label_publisher_summary: "Editorial:",
        label_user_summary: "Usuario:",
        tooltip_support_change: "Si desea cambiar esto, póngase en contacto con soporte.",
        link_need_help: "¿Necesita ayuda?",
        link_forgot_password: "olvidé contraseña",
        divider_or: "----o----",
        divider_or_long: "----------------o-----------------",
        msg_confirm_delete_book: "¿Seguro que desea eliminar este libro?",
        msg_warning_delete_book: "Esta ação eliminará el libro del catálogo.",
        msg_confirm_delete_publisher: "¿Seguro que desea eliminar esta editorial?",
        msg_warning_delete_irreversible: "Esta acción no se puede deshacer.",
        msg_confirm_delete_rental: "¿Seguro que desea eliminar este registro de alquiler?",
        msg_confirm_return_rental: "¿Desea confirmar la devolución de este libro?",
        msg_confirm_change_status: "¿Desea cambiar el estado de este usuario?",
        msg_warning_change_status: "El usuario perderá el acceso si se desactiva.",
        banner_welcome: "Bienvenido(a)",
        banner_line2: "La Lectura Abre",
        banner_line3: "Nuevos Mundos",
        banner_line4: "Acceda a su cuenta y disfrute de su experiencia",
        title_recover_pwd: "Recuperar Contraseña",
        title_form_welcome: "¡Bienvenido(a)!",
        footer_about_title: "Sobre Nosotros",
        footer_about_mobile: "Creando valor e inspiración desde 2023.",
        footer_about_desktop: "Creando valor e inspiración desde 2023.\nNuestra misión es conectar con sus productos de forma práctica.",
        footer_contact_title: "Contáctenos",
        footer_locations_title: "Nuestras Sedes",
        location_1: "Calle Padre Filho, 263 - Centro",
        location_2: "Calle IV, 60 - Paulista",
        location_3: "Calle Norte Europeo, 110 - Vale Central"
    }
};

function applyLanguage(lang) {
    if (!translations[lang]) return;

    localStorage.setItem("app_language", lang);
    document.documentElement.lang = lang === 'pt' ? 'pt-BR' : lang;

    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        if (translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
        const key = el.getAttribute("data-i18n-placeholder");
        if (translations[lang][key]) {
            el.setAttribute("placeholder", translations[lang][key]);
        }
    });

    document.querySelectorAll("[data-i18n-title]").forEach(el => {
        const key = el.getAttribute("data-i18n-title");
        if (translations[lang][key]) {
            el.setAttribute("title", translations[lang][key]);
        }
    });
}

document.addEventListener("DOMContentLoaded", () => {
    const savedLang = localStorage.getItem("app_language") || "pt";
    applyLanguage(savedLang);

    const langSelect = document.getElementById("select-language");
    if (langSelect) {
        langSelect.value = savedLang;
        langSelect.addEventListener("change", (e) => {
            applyLanguage(e.target.value);
        });
    }
});